name: CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm clean-install

  linter:
    needs: [ dependencies ]
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - name: Run linter
        run: npm run test:lint

  type-check:
    needs: [ dependencies ]
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - name: Run type check
        run: npm run test:tsc

  unit-tests:
    needs: [ dependencies ]
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - name: Run unit tests
        run: npm run test:unit

  compile-bundle:
    name: Compile Bundle from Source
    needs: [ linter, type-check, unit-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - name: Compile bundle with Rollup
        run: |
          npm run clean
          npm run build:rollup
      - uses: actions/upload-artifact@v4
        with:
          name: d2cli-bundle-cjs
          path: ./dist/d2cli.cjs

  linux-binary:
    name: Build Native Linux Binary
    needs: [ compile-bundle ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - uses: actions/download-artifact@v4
        with:
          name: d2cli-bundle-cjs
          path: ./dist
      - name: Build native binary
        run: npm run build:nexe:linux
      - uses: actions/upload-artifact@v4
        with:
          name: d2cli-bin-linux
          path: ./.bin/d2cli-linux

  macos-binary:
    name: Build Native macOS Binary
    needs: [ compile-bundle ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - uses: actions/download-artifact@v4
        with:
          name: d2cli-bundle-cjs
          path: ./dist
      - name: Build native binary
        run: npm run build:nexe:macos
      - uses: actions/upload-artifact@v4
        with:
          name: d2cli-bin-macos
          path: ./.bin/d2cli-macos

  windows-binary:
    name: Build Native Windows Binary
    needs: [ compile-bundle ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache-working-directory
        with:
          path: '.'
          key: ${{ github.event_name }}-${{ github.sha }}-${{ runner.os }}-working-directory
      - uses: actions/download-artifact@v4
        with:
          name: d2cli-bundle-cjs
          path: ./dist
      - name: Build native binary
        run: npm run build:nexe:windows
      - uses: actions/upload-artifact@v4
        with:
          name: d2cli-bin-windows
          path: ./.bin/d2cli-windows.exe

  pre-release:
    name: Pre-Release Check
    needs: [ linux-binary, macos-binary, windows-binary ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    steps:
      - run: echo "Pre-Release Check"

  release:
    name: Create Release
    needs: [ pre-release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: d2cli-bin-linux
          path: ./.bin
      - uses: actions/download-artifact@v4
        with:
          name: d2cli-bin-macos
          path: ./.bin
      - uses: actions/download-artifact@v4
        with:
          name: d2cli-bin-windows
          path: ./.bin
      - run: ls -al ./.bin
